---

# Run apt update
- name: Run apt update 
  apt: 
    update_cache: yes

# Install requirements 
- name: Install requirements - apt-transport-https
  apt: 
    name: apt-transport-https
    state: latest 

- name: Install requirements - ca-certificates
  apt: 
    name: ca-certificates
    state: latest 

- name: Install requirements - curl
  apt: 
    name: curl
    state: latest 

- name: Install requirements - software-properties-common
  apt: 
    name: software-properties-common
    state: latest 

- name: Install requirements - python-pip
  apt: 
    name: python-pip
    state: latest 

- name: Install requirements - python3-pip
  apt: 
    name: python3-pip
    state: latest 

- name: Install requirements - virtualenv
  apt: 
    name: virtualenv
    state: latest 

- name: Install requirements - python3-setuptools
  apt: 
    name: python3-setuptools
    state: latest 


# Add gpg key for docker
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# Add Docker apt repocitory  
- name: Add Docker apt repository 
  ansible.builtin.apt_repository: 
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present 

# Install Docker 
- name: Install Docker 
  apt: 
    name: docker-ce
    update_cache: yes 
    state: latest

# Install pip modules     
- name: Install pip modules
  shell: 
    cmd: pip install docker
    executable: /bin/bash
